<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260323120109 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE answers (id UUID NOT NULL, content TEXT NOT NULL, is_from_ai BOOLEAN NOT NULL, author_id UUID DEFAULT NULL, moderation_status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, round_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_50D0C606F675F31B ON answers (author_id)');
        $this->addSql('CREATE INDEX IDX_50D0C606A6005CA0 ON answers (round_id)');
        $this->addSql('CREATE TABLE games (id UUID NOT NULL, code VARCHAR(6) DEFAULT NULL, status VARCHAR(255) NOT NULL, is_private BOOLEAN NOT NULL, winner_id UUID DEFAULT NULL, winner_type VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FF232B3177153098 ON games (code)');
        $this->addSql('CREATE INDEX IDX_FF232B3177153098 ON games (code)');
        $this->addSql('CREATE INDEX IDX_FF232B317B00651C ON games (status)');
        $this->addSql('CREATE TABLE game_players (game_id UUID NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (game_id, user_id))');
        $this->addSql('CREATE INDEX IDX_B38C3C89E48FD905 ON game_players (game_id)');
        $this->addSql('CREATE INDEX IDX_B38C3C89A76ED395 ON game_players (user_id)');
        $this->addSql('CREATE TABLE moderation_logs (id UUID NOT NULL, content TEXT NOT NULL, flagged_reason VARCHAR(255) NOT NULL, game_id UUID DEFAULT NULL, user_id UUID DEFAULT NULL, timestamp TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_13191A4EE48FD905 ON moderation_logs (game_id)');
        $this->addSql('CREATE INDEX IDX_13191A4EA76ED395 ON moderation_logs (user_id)');
        $this->addSql('CREATE TABLE votes (id UUID NOT NULL, voter_id UUID NOT NULL, answer_id UUID NOT NULL, voted_as_ai BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, round_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_518B7ACFEBB4B8AD ON votes (voter_id)');
        $this->addSql('CREATE INDEX IDX_518B7ACFAA334807 ON votes (answer_id)');
        $this->addSql('CREATE INDEX IDX_518B7ACFA6005CA0 ON votes (round_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE answers ADD CONSTRAINT FK_50D0C606A6005CA0 FOREIGN KEY (round_id) REFERENCES rounds (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE answers ADD CONSTRAINT FK_50D0C606F675F31B FOREIGN KEY (author_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_players ADD CONSTRAINT FK_B38C3C89E48FD905 FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE game_players ADD CONSTRAINT FK_B38C3C89A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE moderation_logs ADD CONSTRAINT FK_13191A4EE48FD905 FOREIGN KEY (game_id) REFERENCES games (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE moderation_logs ADD CONSTRAINT FK_13191A4EA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE votes ADD CONSTRAINT FK_518B7ACFEBB4B8AD FOREIGN KEY (voter_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE votes ADD CONSTRAINT FK_518B7ACFAA334807 FOREIGN KEY (answer_id) REFERENCES answers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE votes ADD CONSTRAINT FK_518B7ACFA6005CA0 FOREIGN KEY (round_id) REFERENCES rounds (id) NOT DEFERRABLE');
        $this->addSql('DROP TABLE game');
        $this->addSql('ALTER TABLE rounds DROP CONSTRAINT fk_rounds_game');
        $this->addSql('ALTER TABLE rounds ADD CONSTRAINT FK_3A7FD554E48FD905 FOREIGN KEY (game_id) REFERENCES games (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_rounds_question_master_id RENAME TO IDX_3A7FD5541A669F8A');
        $this->addSql('ALTER INDEX idx_rounds_eliminated_player_id RENAME TO IDX_3A7FD554B96971E1');
        $this->addSql('ALTER INDEX idx_rounds_game_id RENAME TO IDX_3A7FD554E48FD905');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E986CC499D ON users (pseudo)');
        $this->addSql('ALTER INDEX users_email_key RENAME TO UNIQ_1483A5E9E7927C74');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE game (id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE answers DROP CONSTRAINT FK_50D0C606A6005CA0');
        $this->addSql('ALTER TABLE answers DROP CONSTRAINT FK_50D0C606F675F31B');
        $this->addSql('ALTER TABLE game_players DROP CONSTRAINT FK_B38C3C89E48FD905');
        $this->addSql('ALTER TABLE game_players DROP CONSTRAINT FK_B38C3C89A76ED395');
        $this->addSql('ALTER TABLE moderation_logs DROP CONSTRAINT FK_13191A4EE48FD905');
        $this->addSql('ALTER TABLE moderation_logs DROP CONSTRAINT FK_13191A4EA76ED395');
        $this->addSql('ALTER TABLE votes DROP CONSTRAINT FK_518B7ACFEBB4B8AD');
        $this->addSql('ALTER TABLE votes DROP CONSTRAINT FK_518B7ACFAA334807');
        $this->addSql('ALTER TABLE votes DROP CONSTRAINT FK_518B7ACFA6005CA0');
        $this->addSql('DROP TABLE answers');
        $this->addSql('DROP TABLE games');
        $this->addSql('DROP TABLE game_players');
        $this->addSql('DROP TABLE moderation_logs');
        $this->addSql('DROP TABLE votes');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE rounds DROP CONSTRAINT FK_3A7FD554E48FD905');
        $this->addSql('ALTER TABLE rounds ADD CONSTRAINT fk_rounds_game FOREIGN KEY (game_id) REFERENCES game (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_3a7fd5541a669f8a RENAME TO idx_rounds_question_master_id');
        $this->addSql('ALTER INDEX idx_3a7fd554e48fd905 RENAME TO idx_rounds_game_id');
        $this->addSql('ALTER INDEX idx_3a7fd554b96971e1 RENAME TO idx_rounds_eliminated_player_id');
        $this->addSql('DROP INDEX UNIQ_1483A5E986CC499D');
        $this->addSql('ALTER INDEX uniq_1483a5e9e7927c74 RENAME TO users_email_key');
    }
}
