<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260209134905 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create question_category table and insert initial categories';
    }

    public function up(Schema $schema): void
    {
        // Création de la table
        $this->addSql('CREATE TABLE question_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6544A9CD5E237E06 ON question_category (name)');

        // Insertion des catégories
        $categories = [
            'films et cinéma',
            'séries télévisées',
            'musique et artistes',
            'concerts et festivals',
            'voyages et destinations',
            'pays et cultures',
            'enfance et souvenirs',
            'nourriture et cuisine',
            'restaurants et gastronomie',
            'boissons et cocktails',
            'technologie et gadgets',
            'réseaux sociaux',
            'jeux vidéo',
            'sports et compétitions',
            'activités physiques',
            'sports extrêmes',
            'animaux domestiques',
            'animaux sauvages',
            'métiers et professions',
            'vie au travail',
            'études et école',
            'habitudes quotidiennes',
            'routines matinales ou nocturnes',
            'rêves et ambitions',
            'projets futurs',
            'relations familiales',
            'amitié et rencontres',
            'amour et couple',
            'loisirs créatifs',
            'art et peinture',
            'lecture et livres',
            'nature et randonnées',
            'écologie et environnement',
            'saisons et météo',
            'fêtes et célébrations',
            'vacances et jours fériés',
            'mode et vêtements',
            'coiffure et style',
            'maison et décoration',
            'jardinage et plantes',
            'véhicules et conduite',
            'transports en commun',
            'shopping et achats',
            'argent et budget',
            'santé et bien-être',
            'sommeil et repos',
            'peurs et phobies',
            'superstitions et croyances',
            'langues étrangères',
            'histoires drôles et anecdotes',
            'héros et personnages fictifs',
            'science et découvertes',
            'espace et astronomie',
            'histoire et époques',
            'géographie et villes',
            'architecture et monuments',
            'photographie et images',
            'danse et chorégraphie',
            'théâtre et spectacles',
            'podcasts et émissions',
            'actualités et tendances',
            'internet et mèmes',
            'collections et objets'
        ];

        foreach ($categories as $category) {
            $this->addSql('INSERT INTO question_category (name, is_active) VALUES (:name, true)', ['name' => $category]);
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE question_category');
    }
}