<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260323112853 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial database schema with all tables and question categories seeding';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE answers (id UUID NOT NULL, content TEXT NOT NULL, is_from_ai BOOLEAN NOT NULL, author_id UUID DEFAULT NULL, moderation_status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, round_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_50D0C606F675F31B ON answers (author_id)');
        $this->addSql('CREATE INDEX IDX_50D0C606A6005CA0 ON answers (round_id)');
        $this->addSql('CREATE TABLE games (id UUID NOT NULL, code VARCHAR(6) DEFAULT NULL, status VARCHAR(255) NOT NULL, is_private BOOLEAN NOT NULL, winner_id UUID DEFAULT NULL, winner_type VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FF232B3177153098 ON games (code)');
        $this->addSql('CREATE INDEX IDX_FF232B3177153098 ON games (code)');
        $this->addSql('CREATE INDEX IDX_FF232B317B00651C ON games (status)');
        $this->addSql('CREATE TABLE game_players (game_id UUID NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (game_id, user_id))');
        $this->addSql('CREATE INDEX IDX_B38C3C89E48FD905 ON game_players (game_id)');
        $this->addSql('CREATE INDEX IDX_B38C3C89A76ED395 ON game_players (user_id)');
        $this->addSql('CREATE TABLE moderation_logs (id UUID NOT NULL, content TEXT NOT NULL, flagged_reason VARCHAR(255) NOT NULL, game_id UUID DEFAULT NULL, user_id UUID DEFAULT NULL, timestamp TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_13191A4EE48FD905 ON moderation_logs (game_id)');
        $this->addSql('CREATE INDEX IDX_13191A4EA76ED395 ON moderation_logs (user_id)');
        $this->addSql('CREATE TABLE question_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6544A9CD5E237E06 ON question_category (name)');
        $this->addSql('CREATE TABLE rounds (id UUID NOT NULL, round_number INT NOT NULL, question TEXT DEFAULT NULL, question_master_id UUID NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, game_id UUID NOT NULL, eliminated_player_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3A7FD5541A669F8A ON rounds (question_master_id)');
        $this->addSql('CREATE INDEX IDX_3A7FD554B96971E1 ON rounds (eliminated_player_id)');
        $this->addSql('CREATE INDEX IDX_3A7FD554E48FD905 ON rounds (game_id)');
        $this->addSql('CREATE TABLE users (id UUID NOT NULL, email VARCHAR(180) NOT NULL, pseudo VARCHAR(50) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E986CC499D ON users (pseudo)');
        $this->addSql('CREATE TABLE votes (id UUID NOT NULL, voter_id UUID NOT NULL, answer_id UUID NOT NULL, voted_as_ai BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, round_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_518B7ACFEBB4B8AD ON votes (voter_id)');
        $this->addSql('CREATE INDEX IDX_518B7ACFAA334807 ON votes (answer_id)');
        $this->addSql('CREATE INDEX IDX_518B7ACFA6005CA0 ON votes (round_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        
        $this->addSql('ALTER TABLE answers ADD CONSTRAINT FK_50D0C606A6005CA0 FOREIGN KEY (round_id) REFERENCES rounds (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE answers ADD CONSTRAINT FK_50D0C606F675F31B FOREIGN KEY (author_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_players ADD CONSTRAINT FK_B38C3C89E48FD905 FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE game_players ADD CONSTRAINT FK_B38C3C89A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE moderation_logs ADD CONSTRAINT FK_13191A4EE48FD905 FOREIGN KEY (game_id) REFERENCES games (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE moderation_logs ADD CONSTRAINT FK_13191A4EA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rounds ADD CONSTRAINT FK_3A7FD554E48FD905 FOREIGN KEY (game_id) REFERENCES games (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rounds ADD CONSTRAINT FK_3A7FD5541A669F8A FOREIGN KEY (question_master_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rounds ADD CONSTRAINT FK_3A7FD554B96971E1 FOREIGN KEY (eliminated_player_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE votes ADD CONSTRAINT FK_518B7ACFEBB4B8AD FOREIGN KEY (voter_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE votes ADD CONSTRAINT FK_518B7ACFAA334807 FOREIGN KEY (answer_id) REFERENCES answers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE votes ADD CONSTRAINT FK_518B7ACFA6005CA0 FOREIGN KEY (round_id) REFERENCES rounds (id) NOT DEFERRABLE');

        $categories = [
            'Voyage et aventure', 'Nourriture et cuisine', 'Musique et sons',
            'Animaux et nature', 'Enfance et souvenirs', 'Sport et compétition',
            'Films et séries', 'Technologie et gadgets', 'Rêves et imagination',
            'Peurs et phobies', 'Amitié et relations', 'Argent et achats',
            'Humour et blagues', 'Couleurs et esthétique', 'Métiers et ambitions',
            'Jeux et divertissements', 'Saisons et météo', 'Habitudes et rituels',
            'Superpouvoir et fiction', 'Histoire et culture',
        ];

        foreach ($categories as $name) {
            $this->addSql(
                "INSERT INTO question_category (name, is_active) VALUES (:name, true)",
                ['name' => $name]
            );
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE answers DROP CONSTRAINT FK_50D0C606A6005CA0');
        $this->addSql('ALTER TABLE answers DROP CONSTRAINT FK_50D0C606F675F31B');
        $this->addSql('ALTER TABLE game_players DROP CONSTRAINT FK_B38C3C89E48FD905');
        $this->addSql('ALTER TABLE game_players DROP CONSTRAINT FK_B38C3C89A76ED395');
        $this->addSql('ALTER TABLE moderation_logs DROP CONSTRAINT FK_13191A4EE48FD905');
        $this->addSql('ALTER TABLE moderation_logs DROP CONSTRAINT FK_13191A4EA76ED395');
        $this->addSql('ALTER TABLE rounds DROP CONSTRAINT FK_3A7FD554E48FD905');
        $this->addSql('ALTER TABLE rounds DROP CONSTRAINT FK_3A7FD5541A669F8A');
        $this->addSql('ALTER TABLE rounds DROP CONSTRAINT FK_3A7FD554B96971E1');
        $this->addSql('ALTER TABLE votes DROP CONSTRAINT FK_518B7ACFEBB4B8AD');
        $this->addSql('ALTER TABLE votes DROP CONSTRAINT FK_518B7ACFAA334807');
        $this->addSql('ALTER TABLE votes DROP CONSTRAINT FK_518B7ACFA6005CA0');
        $this->addSql('DROP TABLE answers');
        $this->addSql('DROP TABLE games');
        $this->addSql('DROP TABLE game_players');
        $this->addSql('DROP TABLE moderation_logs');
        $this->addSql('DROP TABLE question_category');
        $this->addSql('DROP TABLE rounds');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE votes');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
