<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260209134905 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create question_category table, insert initial categories, and create AI user';
    }

    public function up(Schema $schema): void
    {

        // Création de la table users
        $this->addSql('CREATE TABLE users (
            id UUID NOT NULL PRIMARY KEY,
            email VARCHAR(180) NOT NULL UNIQUE,
            pseudo VARCHAR(50) NOT NULL,
            password VARCHAR(255) NOT NULL,
            roles JSON NOT NULL
        )');

        // Création de la table game (structure minimale pour la FK)
        $this->addSql('CREATE TABLE game (
            id UUID NOT NULL PRIMARY KEY
        )');

        // Création de la table rounds (pour correspondre à l'entité Round)
        $this->addSql('CREATE TABLE rounds (
            id UUID NOT NULL PRIMARY KEY,
            round_number INT NOT NULL,
            question TEXT DEFAULT NULL,
            question_master_id UUID NOT NULL,
            status VARCHAR(255) NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            game_id UUID NOT NULL,
            eliminated_player_id UUID DEFAULT NULL,
            CONSTRAINT FK_ROUNDS_GAME FOREIGN KEY (game_id) REFERENCES game (id) NOT DEFERRABLE INITIALLY IMMEDIATE,
            CONSTRAINT FK_ROUNDS_QUESTION_MASTER FOREIGN KEY (question_master_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE,
            CONSTRAINT FK_ROUNDS_ELIMINATED_PLAYER FOREIGN KEY (eliminated_player_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        )');
        $this->addSql('CREATE INDEX IDX_ROUNDS_GAME_ID ON rounds (game_id)');
        $this->addSql('CREATE INDEX IDX_ROUNDS_QUESTION_MASTER_ID ON rounds (question_master_id)');
        $this->addSql('CREATE INDEX IDX_ROUNDS_ELIMINATED_PLAYER_ID ON rounds (eliminated_player_id)');

        // Création de la table question_category
        $this->addSql('CREATE TABLE question_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6544A9CD5E237E06 ON question_category (name)');

        // Insertion des catégories
        $categories = [
            'films et cinéma',
            'séries télévisées',
            'musique et artistes',
            'concerts et festivals',
            'voyages et destinations',
            'pays et cultures',
            'enfance et souvenirs',
            'nourriture et cuisine',
            'restaurants et gastronomie',
            'boissons et cocktails',
            'technologie et gadgets',
            'réseaux sociaux',
            'jeux vidéo',
            'sports et compétitions',
            'activités physiques',
            'sports extrêmes',
            'animaux domestiques',
            'animaux sauvages',
            'métiers et professions',
            'vie au travail',
            'études et école',
            'habitudes quotidiennes',
            'routines matinales ou nocturnes',
            'rêves et ambitions',
            'projets futurs',
            'relations familiales',
            'amitié et rencontres',
            'amour et couple',
            'loisirs créatifs',
            'art et peinture',
            'lecture et livres',
            'nature et randonnées',
            'écologie et environnement',
            'saisons et météo',
            'fêtes et célébrations',
            'vacances et jours fériés',
            'mode et vêtements',
            'coiffure et style',
            'maison et décoration',
            'jardinage et plantes',
            'véhicules et conduite',
            'transports en commun',
            'shopping et achats',
            'argent et budget',
            'santé et bien-être',
            'sommeil et repos',
            'peurs et phobies',
            'superstitions et croyances',
            'langues étrangères',
            'histoires drôles et anecdotes',
            'héros et personnages fictifs',
            'science et découvertes',
            'espace et astronomie',
            'histoire et époques',
            'géographie et villes',
            'architecture et monuments',
            'photographie et images',
            'danse et chorégraphie',
            'théâtre et spectacles',
            'podcasts et émissions',
            'actualités et tendances',
            'internet et mèmes',
            'collections et objets'
        ];

        foreach ($categories as $category) {
            $this->addSql('INSERT INTO question_category (name, is_active) VALUES (:name, true)', ['name' => $category]);
        }

        // Création de l'utilisateur IA
        $this->addSql("
            INSERT INTO users (id, email, pseudo, password, roles) 
            VALUES (
                gen_random_uuid(), 
                'ai@parry.game', 
                'IA-PARRY', 
                '\$2y\$13\$dummyHashThatWillNeverBeUsedForAI', 
                '[\"ROLE_AI\"]'
            )
            ON CONFLICT (email) DO NOTHING
        ");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE question_category');
        $this->addSql("DELETE FROM users WHERE email = 'ai@parry.game'");
    }
}