<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260521160934 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE animal_configs (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, alias VARCHAR(50) NOT NULL, animal_name VARCHAR(100) NOT NULL, response_sprite VARCHAR(255) NOT NULL, question_sprite VARCHAR(255) NOT NULL, elimination_sprite VARCHAR(255) NOT NULL, color VARCHAR(7) DEFAULT NULL, description TEXT DEFAULT NULL, sound_effects JSON DEFAULT NULL, particles VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CDB61709E16C6B94 ON animal_configs (alias)');
        $this->addSql('CREATE TABLE game_player_aliases (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, assigned_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, game_id UUID NOT NULL, player_id UUID NOT NULL, animal_config_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E42C1830E48FD905 ON game_player_aliases (game_id)');
        $this->addSql('CREATE INDEX IDX_E42C183099E6F5DF ON game_player_aliases (player_id)');
        $this->addSql('CREATE INDEX IDX_E42C1830DC7F2BEC ON game_player_aliases (animal_config_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E42C1830E48FD90599E6F5DF ON game_player_aliases (game_id, player_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E42C1830E48FD905DC7F2BEC ON game_player_aliases (game_id, animal_config_id)');
        $this->addSql('ALTER TABLE game_player_aliases ADD CONSTRAINT FK_E42C1830E48FD905 FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_player_aliases ADD CONSTRAINT FK_E42C183099E6F5DF FOREIGN KEY (player_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_player_aliases ADD CONSTRAINT FK_E42C1830DC7F2BEC FOREIGN KEY (animal_config_id) REFERENCES animal_configs (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE game_player_aliases DROP CONSTRAINT FK_E42C1830E48FD905');
        $this->addSql('ALTER TABLE game_player_aliases DROP CONSTRAINT FK_E42C183099E6F5DF');
        $this->addSql('ALTER TABLE game_player_aliases DROP CONSTRAINT FK_E42C1830DC7F2BEC');
        $this->addSql('DROP TABLE animal_configs');
        $this->addSql('DROP TABLE game_player_aliases');
    }
}
