parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
        
        
    App\Service\AI\GeminiClient:
        arguments:
            $apiUrl: '%env(GEMINI_API_URL)%'
            $apiKey: '%env(GEMINI_API_KEY)%'
            $model: '%env(GEMINI_MODEL)%'